### ISSUE TITLE
无法测试网络请求数据缓存

### ISSUE THREAD

**Issue by jiaoshier** [casatwy/CTNetworking#10]
在进行网络请求用例测试时，发现无法进行缓存，打印日志查看最终定位到CTResponse初始化的时候
self.acturlRequestParams = request.actualRequestParams;
self.originRequestParams = request.originRequestParams;
这俩个方法的数据都是nil，不知道是方法错误还是是买问题，希望可以解释一下，谢谢

**Comment by casatwy** [comment]
actualRequestParams和originRequestParams都是要在你自己的service生成request的时候去给的。

**Comment by jiaoshier** [comment]
好的，我回头在测试一下，谢谢
