### ISSUE TITLE
Can upload image or files ?

### ISSUE THREAD

**Issue by wwwang89** [casatwy/CTNetworking#12]
I test CTNetworking ,it may not support upload image files ? is't it ?
or how can I do to support upload images ?thanks!

**Comment by casatwy** [comment]
CTNetworking不支持文件上传、下载。

因为：

1. CTNetworking的设计初衷仅限于API调用。

2. 文件上传部分各家公司的实现都是不一样的，甚至直接使用的是别的第三方的SDK（例如七牛云存储）来做文件上传。所以CTNetworking没有办法给上传操作一个统一实现。

3. 文件下载部分，AFNetworking已经做得很好了，CTNetworking没有必要重复封装。
