### ISSUE TITLE
CTAPIBaseManager 这个类  每次发送请求都要写一个子类继承它吗

### ISSUE THREAD

**Issue by pengzhiqiang110** [casatwy/CTNetworking#15]
比如一个控制器里面需要发送两次请求,需要写两个子类分别继承CTAPIBaseManager,然后再分别在子类中实现代理方法  (NSString *_Nonnull)methodName 等等吗?如果这样的话  感觉挺麻烦的,可不可以写一个CTAPIBaseManager子类  然后在代理方法中加参数,区分是哪个请求,再返回对应请求的methodName值.期待你的回复

**Comment by casatwy** [comment]
你可以参考我readme里面给到的MarvelAPI的那个工程，里面有一个bash脚本，用于APIManager的代码生成。

有脚本来生成代码，methodName这事儿你就不会觉得麻烦了。如果按照你说的做法，对架构的破坏比较大的。

**Comment by batmanNolan** [comment]
想问一下，如果工程里面有上百个请求，这样写会导致文件数量非常多，而且在同一个页面有多个请求的情况下，需要在delegate中进行区分，这样各种逻辑的代码还是会在一起而且需要用ifelse进行分区

**Comment by casatwy** [comment]
1. 文件多会导致什么问题？

2. 使用strategy就不会导致if-else的出现。

**Comment by casatwy** [comment]
> 想问一下，如果工程里面有上百个请求，这样写会导致文件数量非常多，而且在同一个页面有多个请求的情况下，需要在delegate中进行区分，这样各种逻辑的代码还是会在一起而且需要用ifelse进行分区

1. 文件多会导致什么问题？

2. 使用strategy就不会导致if-else的出现。
