### ISSUE TITLE
返回数据格式问题

### ISSUE THREAD

**Issue by YearRen** [casatwy/CTNetworking#17]
casa大神，你好，我想请教一个问题，后台返回格式是json格式，但是我在断点调试的时候CTApiProxy.m这个类中的接收数据是直接用data接收的，这样导致进入日志CTLogger类中的时候就会崩溃，请问是需要设置什么么

**Comment by casatwy** [comment]
你可以参考readme中给到的示例工程的做法。

一个是高德地图API，一个是漫威API

**Comment by YearRen** [comment]
一直没有看到有高德api的示例，刚才下载跑起来直接直接崩溃了，高德这边返回的是json格式，但是接收类型是NSData,
![image](https://user-images.githubusercontent.com/13882689/45537736-a7a32880-b837-11e8-9a85-9b66db1fc619.png)

**Comment by YearRen** [comment]
@casatwy  这个我知道，其实我纠结的点在CTLogger这里，Service protocol 处理业务逻辑，但是CTLogger.m中，如果数据格式不是data，而是json的话在这个有个data转string的方法就会崩溃
![image](https://user-images.githubusercontent.com/13882689/45729838-fae2f580-bc00-11e8-9647-4cb1122835de.png)
这个虽然是在debug模式下的，我不知道这里是否应该也需要处理一下还是说这里直接注释掉就完了呢

**Comment by casatwy** [comment]
我记得我给到的rawResponseData应该就是NSData

**Comment by YearRen** [comment]
@casatwy 在CTApiProxy.m中的100行给的是af回调中的responseData，这里的responseData有可能是dictionary、有可能是data，我跑高德api那个demo的时候这里的responseData是dictionary
![image](https://user-images.githubusercontent.com/13882689/45732262-11437e00-bc0e-11e8-9144-379faf3de329.png)

**Comment by casatwy** [comment]
应该是我高德Service在生成request时候的锅，我没有给一个content-type的header
