### ISSUE TITLE
pod search 出来的貌似不是你的这个

### ISSUE THREAD

**Issue by lizhaobomb** [casatwy/CTNetworking#2]
-> CTNetworking (1.0.0)
   CTNetworking is an iOS discrete HTTP API calling framework based on
   AFNetworking.
   pod 'CTNetworking', '~> 1.0.0'
   - Homepage: https://github.com/Corotata/RTNetworking
   - Source:   https://github.com/Corotata/RTNetworking.git
   - Versions: 1.0.0 [master repo]
(END)

**Comment by casatwy** [comment]
corotata以前fork过我的代码，可能他误操作了。现在他已经把owner还给我了。

发自我的 iPhone

在 2018年2月28日，18:20，lizhaobomb <notifications@github.com<mailto:notifications@github.com>> 写道：


-> CTNetworking (1.0.0)
CTNetworking is an iOS discrete HTTP API calling framework based on
AFNetworking.
pod 'CTNetworking', '~> 1.0.0'

  *   Homepage: https://github.com/Corotata/RTNetworking
  *   Source: https://github.com/Corotata/RTNetworking.git
  *   Versions: 1.0.0 [master repo]
(END)
