### ISSUE TITLE
这个项目跟原来的 RTNetworking 有什么不同吗

### ISSUE THREAD

**Issue by ShannonChenCHN** [casatwy/CTNetworking#3]
很好奇为什么不是直接在原来 RTNetworking 的基础上进行迭代，而是新开了个 repo？是因为改动会比较大的原因吗？

**Comment by casatwy** [comment]
主要的API调度机制没变，其它改变了CTAppContext的获取方式和CTService的机制。

现在的CTNetworking是这几年对RTNerworking的调整。

发自我的 iPhone

在 2018年3月1日，16:22，ShannonChen <notifications@github.com<mailto:notifications@github.com>> 写道：

**Comment by ShannonChenCHN** [comment]
一直没搞明白 CTAppContext 的作用是什么😂

原来的 RTNetworking 中好像没有实现缓存机制，还有就是如果能添加一个像 YTKNetwork 中的 [YTKRequestAccessory](@protocol YTKRequestAccessory <NSObject>) 那样能显示 toast 的插件就好了。

**Comment by casatwy** [comment]
现在的CTNetworking支持缓存了

ctappcontext的作用主要是指导CTNetworking行为的

弹toast不是一个网络库该做的事情，但我提供了intercept，可以在那里面自定义弹toast

发自我的 iPhone

在 2018年3月1日，16:30，ShannonChen <notifications@github.com<mailto:notifications@github.com>> 写道：


一直没搞明白 CTAppContext 的作用是什么😂

原来的 RTNetworking 中好像没有实现缓存机制，还有就是如果能添加一个像 YTKNetwork 中的 [YTKRequestAccessory](@protocol<https://github.com/protocol> YTKRequestAccessory ) 那样能显示 toast 的插件就好了。
