### ISSUE TITLE
日志打印body为N/A

### ISSUE THREAD

**Issue by TLcv** [casatwy/CTNetworking#33]
- (id)CT_defaultValue:(id)defaultData
{
    if (![defaultData isKindOfClass:[self class]]) {
  //此处判断由于defaultData为__NSCFConstantString
//self为NSTaggedPointerString，由于类型不同，导致不能准确打印参数
        return defaultData;
    }
    
    if ([self CT_isEmptyObject]) {
        return defaultData;
    }
    
    return self;
}

**Comment by casatwy** [comment]
新的版本号是15，你试试看？
