### ISSUE TITLE
AFHTTPSessionManager的使用

### ISSUE THREAD

**Issue by YearRen** [casatwy/CTNetworking#34]
AFHTTPSessionManager manager 不是单例，请求成功task没有收回，看到AF提问区有人回答需要调用 AFHTTPSessionManager 的 invalidateSessionCancelingTasks:resetSession: ，CTNetworking中并没有暴露AFHTTPSessionManager，所以是否需要在收到resultWithResponseObject:response:request:error:之前invalidateSessionCancelingTasks:resetSession:

**Comment by casatwy** [comment]
在我的设计里，sessionManager是让service返回的，service是CTNetworking的使用者给到的，所以CTNetworking就不暴露AFHTTPSessionManager了
