### ISSUE TITLE
可否提供类图?

### ISSUE THREAD

**Issue by ChenTF** [casatwy/CTNetworking#4]
您好, 可否提供类图?
这样有利于更快速的理解项目中类之间的逻辑关系.

**Comment by casatwy** [comment]
CT_Marvel是个很好的实例工程，单步追踪调试会更好理解一些。

你看源码会发现CTNetworking本身没有几个类，所以就不提供类图了。

发自我的 iPhone

在 2018年3月5日，17:51，陈先生 <notifications@github.com<mailto:notifications@github.com>> 写道：


您好, 可否提供类图?
这样有利于更快速的理解项目中类之间的逻辑关系.

**Comment by ChenTF** [comment]
好的, 我看看.
