### ISSUE TITLE
大佬 commit message也太随意了点吧

### ISSUE THREAD

**Issue by bluesky0109** [casatwy/CTNetworking#5]
如题，能稍微 不那么随意吗 方便大家学习理解每个commit 修改的意义

**Comment by casatwy** [comment]
那是因为我自己写了个alias去做add+commit+push的事情🤷‍♂️

代码的可读性已经很强了，要想知道什么的话看git diff就好了

不想改🤷‍♂️

发自我的 iPhone

在 2018年3月10日，10:02，bluesky <notifications@github.com<mailto:notifications@github.com>> 写道：


如题，能稍微 不那么随意吗 方便大家学习理解每个commit 修改的意义
