### ISSUE TITLE
这个demo关联太多了，没有办法跑起来

### ISSUE THREAD

**Issue by flyOfYW** [casatwy/CTNetworking#7]

**Comment by casatwy** [comment]
pod update

**Comment by flyOfYW** [comment]
我有个疑问，代码有设置这个清除缓存的时间，这个时间是自动将缓存删除的吗

**Comment by casatwy** [comment]
这是缓存过期时间，取出来的时候会做个对比，对比发现过期就删除。如果一直不取，那就不会发现过期，那就不会删除。

缓存是不可能定期删除的，只会是判断是否过期。

**Comment by flyOfYW** [comment]
好的，谢谢呀，#pragma mark - public methods
- (id <CTServiceProtocol>)serviceWithIdentifier:(NSString *)identifier
{
    if (self.serviceStorage[identifier] == nil) {
        self.serviceStorage[identifier] = [self newServiceWithIdentifier:identifier];
    }
    return self.serviceStorage[identifier];
}

#pragma mark - private methods
- (id <CTServiceProtocol>)newServiceWithIdentifier:(NSString *)identifier
{
    return [[CTMediator sharedInstance] performTarget:identifier action:identifier params:nil shouldCacheTarget:NO];
}
这个使用的业务场景是什么情况，看着这代码有点难理解

**Comment by casatwy** [comment]
建议你去追一下CTAPI_Marvel，这是CTNetworking的使用范例

**Comment by flyOfYW** [comment]
ok
