### ISSUE TITLE
这个项目是不是缺少了一些组件？

### ISSUE THREAD

**Issue by coderLCX** [casatwy/CTNetworking#8]
我看过PPT了，PPT中提到的组件，例如AIFService，AIFRequestGenerator，我在这个项目中并未找到，作者可以将完整的网络层源码发一份给我么？谢谢O(∩_∩)O

**Comment by casatwy** [comment]
AIFRequestGenerator和AIFService在这个项目中已经被我拿掉了，因为它并不是一个好的设计，不适用于多App的场景。

**Comment by coderLCX** [comment]
仔细看了下源码，对我启发还是挺大的，非常感谢分享。
另外有几个疑问
1.第一个是validator做数据验证是要求业务方必须做的，这个为什么要这样设计，有时候并没有参数，或者并不需要进行参数验证，这样是不是增加了业务方的使用成本？
2.这个框架并不支持上传，下载这样的请求，如果要进行扩展的话，似乎并不容易。
3.还有一个代码上的疑问：
`- (void)afterPerformSuccessWithResponse:(CTURLResponse *)response
{
    if ((NSInteger)self != (NSInteger)self.interceptor && [self.interceptor respondsToSelector:@selector(manager:afterPerformSuccessWithResponse:)]) {
        [self.interceptor manager:self afterPerformSuccessWithResponse:response];
    }
}`
其中的`(NSInteger)self != (NSInteger)self.interceptor`这行代码意思是manager自己不能成为拦截器吗？为什么这里要做一个NSInteger的类型转换？

**Comment by casatwy** [comment]
1.1 需要对传入参数做验证的API就应该在validator中写入验证逻辑。不需要做参数验证的API，直接return成功就可以了。

1.2 返回数据也需要做验证，有的时候API返回成功，但返回的数据是空数组或者其他不可用的数据，此时进行返回数据验证就能避免很多问题，同时更重要的是针对返回数据的验证能够避免将API成功返回但业务不可用的数据写入缓存。

2. 这个框架只是用来做API调度的，上传下载每个公司的实现都不一样，而且例如七牛这样的公司直接提供了上传下载的SDK，所以我认为没必要在这里做上。

3. 这是指针判断，看是不是同一个对象。如果不是同一个对象的话，就多做一个validator是否实现对应方法的判断。manager自己是可以成为拦截器的。

**Comment by casatwy** [comment]
你问的这些问题我文章下面的评论区都有人问过的，翻墙就能加载评论内容了。

**Comment by imerakk** [comment]
我本来用的shadowsocks，去年19大被封了，现在也没去弄翻墙的VPN了，没找到合适的🤣

**Comment by imerakk** [comment]
CTAPI_Marvel这个项目跑不起来，pod install之后找不到CTAPI_DemoSuite这个依赖，于是我注释了CTAPI_DemoSuite，然后在你的仓库中把CTAPI_DemoSuite这个项目直接下载下来，加到项目中，然后又找不到CTPagableAPIManager的声明。
